name: main
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: any
  cupertino_icons: ^1.0.2
  firebase_core: ^2.22.0
  firebase_auth: ^4.13.0
  cloud_firestore: ^4.13.0
  provider: ^6.1.1
  xml: ^6.0.1
  firebase_ui_auth: ^1.10.0
  go_router: ^12.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/background.png
    - assets/catLol.png
    - assets/homescreen.png

flutter_native_splash:
      image: assets/catLol.png
      color: #42a5f5
      android: true
      ios: true
      title: Your App Name
      color_dark: #000000
      image_dark: assets/splash_screen_dark.png
      status_bar_brightness: light


  # To add custom fonts to your application, add a fonts section here,
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

