name: main
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: any
  cupertino_icons: ^1.0.2
  firebase_core: ^2.22.0
  firebase_auth: ^4.13.0
  cloud_firestore: ^4.13.0
  provider: ^6.1.1
  xml: ^6.0.1
  firebase_ui_auth: 1.7.0
  go_router: ^12.1.1
  geolocator: ^10.1.0
  permission_handler: ^11.0.0
  http: ^1.0.1
  duration_picker: ^1.0.1
  just_audio: ^0.9.35
  audio_service: ^0.18.12
  flutter_local_notifications: ^16.2.0
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
  animate_do: ^3.1.2
  sqflite:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1



# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/background.png
    - assets/catLol.png
    - assets/clearSky.png
    - assets/cloudy.png
    - assets/raining.png
    - assets/snowing.png
    - assets/unlockedTrophy.png
    - assets/lockedTrophy.png
    - assets/backgroundAudio.wav
    - assets/images/

flutter_native_splash:
      image: assets/catLol.png
      color: #42a5f5
      android: true
      ios: true
      title: Your App Name
      color_dark: #000000
      image_dark: assets/splash_screen_dark.png
      status_bar_brightness: light


  # To add custom fonts to your application, add a fonts section here,
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

